name: Java CI with Gradle

on: [push, pull_request]  # Uruchamiaj przy pushu i PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Ustaw zgodnie z wersją w projekcie
          distribution: 'temurin'
      
      - name: Run tests with Gradle
        run: ./gradlew test jacocoTestReport  # Uruchom testy i generuj raport coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml  # Ścieżka do raportu
          fail_ci_if_error: false  # Nie przerywaj CI jeśli upload się nie uda
